version: "3.8"
services:
  dev-db:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce_db
    networks:
      - api
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  api:

volumes:
  pgdata: